version: '3.8'
services:

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  db:
    image: mysql:8.0
    container_name: mysql-media
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: media
      MYSQL_USER: universal-convertor
      MYSQL_PASSWORD: thejoker
    ports:
      - "3307:3306"
    volumes:
      - mysql-media:/var/lib/mysql

  app:
    build: .
    container_name: media-app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/media?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: universal-convertor
      SPRING_DATASOURCE_PASSWORD: thejoker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_KAFKA_BOOTSTRAP_SERVER: kafka:9092
      FILE_UPLOAD_PATH: ./upload/
    depends_on:
      - db
      - kafka

volumes:
  mysql-media:
